CREATE TABLE [dbo].[Cooling_Expense] (
    [Business_Unit]                NVARCHAR (MAX) NULL,
    [Work_Order_Number]            NVARCHAR (MAX) NULL,
    [Region]                       NVARCHAR (50)  NULL,
    [Branch_Code]                  NVARCHAR (MAX) NULL,
    [Payout_Type]                  NVARCHAR (MAX) NULL,
    [Work_Description_Mapped]      NVARCHAR (MAX) NULL,
    [Is_Available_SE]              BIT            NULL,
    [Is_Expenses_Mileage]          BIT            NULL,
    [Is_Expenses_PM]               BIT            NULL,
    [Is_Expenses_Gas]              BIT            NULL,
    [Is_Expenses_Supplies_Repair]  BIT            NULL,
    [Gas_Rate]                     FLOAT (53)     NULL,
    [Supply_Gas_Charges]           FLOAT (53)     NULL,
    [Supplies_Repair_Charges]      FLOAT (53)     NULL,
    [Product]                      NVARCHAR (MAX) NULL,
    [Product_Grouping]             NCHAR (10)     NULL,
    [Distance_Slab]                NCHAR (10)     NULL,
    [Claim]                        FLOAT (53)     NULL,
    [Total_Claim]                  FLOAT (53)     NULL,
    [Labour_Charges]               FLOAT (53)     NULL,
    [Work_Detail_Type]             NVARCHAR (MAX) NULL,
    [Price_Per_Unit_Currency]      NVARCHAR (MAX) NULL,
    [Price_Per_Unit]               NVARCHAR (MAX) NULL,
    [Line_Price_Per_Unit_Currency] NVARCHAR (MAX) NULL,
    [Line_Price_Per_Unit]          NVARCHAR (MAX) NULL,
    [Expense_Quantity]             NVARCHAR (MAX) NULL,
    [Work_Description_Map_Code]    NCHAR (10)     NULL,
    [Work_Description]             NVARCHAR (MAX) NULL,
    [Total_Expense_Currency]       NVARCHAR (MAX) NULL,
    [Total_Expense]                NVARCHAR (MAX) NULL,
    [Work_Order_Type]              NVARCHAR (MAX) NULL,
    [Main_Installed_Product]       NVARCHAR (MAX) NULL,
    [Product_Range]                NVARCHAR (MAX) NULL,
    [Service_Team]                 NVARCHAR (MAX) NULL,
    [Primary_FSR]                  NVARCHAR (MAX) NULL,
    [Work_Detail_Line_Number]      NVARCHAR (MAX) NOT NULL,
    [CSS_Code]                     NVARCHAR (MAX) NULL,
    [Month_Name]                   NVARCHAR (50)  NULL
);

