CREATE TABLE [dbo].[Cooling_Work_Order] (
    [Transaction_ID]                                             BIGINT         IDENTITY (1, 1) NOT NULL,
    [Work_Order_Number]                                          NVARCHAR (50)  NOT NULL,
    [Case]                                                       NVARCHAR (MAX) NULL,
    [PRF_Number]                                                 NVARCHAR (50)  NULL,
    [First_Assigned_DateTime]                                    NVARCHAR (MAX) NULL,
    [Customer_Requested_Date]                                    NVARCHAR (MAX) NULL,
    [FSR_Internal_Comments]                                      NVARCHAR (MAX) NULL,
    [WO_Created_Date_Time]                                       NVARCHAR (MAX) NULL,
    [Main_Installed_Product]                                     NVARCHAR (MAX) NULL,
    [Product]                                                    NVARCHAR (MAX) NULL,
    [Product_Commercial_Reference]                               NVARCHAR (MAX) NULL,
    [Product_Grouping]                                           NCHAR (10)     NULL,
    [IP_Serial_Number]                                           NVARCHAR (MAX) NULL,
    [Work_Order_Reason]                                          NVARCHAR (MAX) NULL,
    [Work_Order_Created_Date]                                    NVARCHAR (MAX) NULL,
    [Completed_On]                                               NVARCHAR (MAX) NULL,
    [Is_Billable]                                                NVARCHAR (MAX) NULL,
    [Is_RepeatCall_NonMeterial]                                  BIT            NULL,
    [Non_Billing_Reason]                                         NVARCHAR (MAX) NULL,
    [Installed_At_Account]                                       NVARCHAR (MAX) NULL,
    [Street]                                                     NVARCHAR (MAX) NULL,
    [City]                                                       NVARCHAR (MAX) NULL,
    [Zip]                                                        NVARCHAR (MAX) NULL,
    [State]                                                      NVARCHAR (MAX) NULL,
    [Service_Team]                                               NVARCHAR (MAX) NULL,
    [Primary_FSR]                                                NVARCHAR (MAX) NULL,
    [Partner_Account]                                            NVARCHAR (MAX) NULL,
    [Partner_Account_Rv]                                         NVARCHAR (MAX) NULL,
    [Work_Performed]                                             NVARCHAR (MAX) NULL,
    [Work_Order_Type]                                            NVARCHAR (MAX) NULL,
    [Contact]                                                    NVARCHAR (MAX) NULL,
    [Contact_Phone]                                              NVARCHAR (MAX) NULL,
    [Work_Order_Sub_Type]                                        NVARCHAR (MAX) NULL,
    [Work_Order_Status]                                          NVARCHAR (MAX) NULL,
    [WO_Completed_Timestamp]                                     NVARCHAR (MAX) NULL,
    [Comments_to_Planner]                                        NVARCHAR (MAX) NULL,
    [Special_Instructions]                                       NVARCHAR (MAX) NULL,
    [Actual_Expense_converted]                                   INT            NULL,
    [Actual_Expense_converted_Currency]                          NVARCHAR (MAX) NULL,
    [Actual_Expense]                                             NVARCHAR (MAX) NULL,
    [Claim_Type]                                                 NVARCHAR (MAX) NULL,
    [CSS_Code]                                                   NVARCHAR (MAX) NULL,
    [Branch_Code]                                                NVARCHAR (MAX) NULL,
    [Payout_Type]                                                NVARCHAR (MAX) NULL,
    [Region]                                                     NVARCHAR (MAX) NULL,
    [Call_type]                                                  NVARCHAR (MAX) NULL,
    [Call_type_rv]                                               NVARCHAR (MAX) NULL,
    [Cooling_Mileage_Actual_Expenses]                            FLOAT (53)     NULL,
    [Cooling_Mileage_Work_Description]                           NVARCHAR (MAX) NULL,
    [Cooling_Gas_Rate]                                           FLOAT (53)     NULL,
    [Cooling_Gas_Actual_Expenses]                                FLOAT (53)     NULL,
    [Cooling_Gas_Work_Description]                               NVARCHAR (MAX) NULL,
    [Cooling_Supplies_Actual_Expenses]                           FLOAT (53)     NULL,
    [Cooling_Supplies_Work_Description]                          NVARCHAR (MAX) NULL,
    [Cooling_Labour_Cost]                                        FLOAT (53)     NULL,
    [Cooling_Supply_Cost]                                        FLOAT (53)     NULL,
    [Cooling_Total_Cost]                                         FLOAT (53)     NULL,
    [PRODUCT_CATEGORY]                                           NVARCHAR (MAX) NULL,
    [Distance_Slab]                                              NVARCHAR (MAX) NULL,
    [Remarks]                                                    NVARCHAR (MAX) NULL,
    [Region_Remarks_If_Any_on_Additional_payout_Repeat_cases_Re] NVARCHAR (MAX) NULL,
    [Bill_Cycle]                                                 NVARCHAR (MAX) NULL,
    [Business_Unit]                                              NVARCHAR (MAX) NULL,
    [DS_Code]                                                    NVARCHAR (MAX) NULL,
    [MaterialUsed]                                               NVARCHAR (MAX) NULL,
    [CSS_Status]                                                 BIT            NULL,
    [CSS_User]                                                   NCHAR (10)     NULL,
    [CSS_UpdateDate]                                             NCHAR (10)     NULL,
    [CSS_Mgr_Status]                                             BIT            NULL,
    [CSS_Remark]                                                 NVARCHAR (MAX) NULL,
    [CSS_Cost]                                                   DECIMAL (20)   NULL,
    [CSS_Mgr_Remark]                                             NVARCHAR (MAX) NULL,
    [CSS_Mgr_Cost]                                               DECIMAL (20)   NULL,
    [CSS_Mgr_User]                                               NVARCHAR (MAX) NULL,
    [CSS_Mgr_UpdateDate]                                         NCHAR (10)     NULL,
    [Central_Approved]                                           BIT            NULL,
    [Actual_Cost]                                                DECIMAL (20)   NULL,
    [Discrepancy]                                                NVARCHAR (MAX) NULL,
    [WO_Process_Status]                                          NCHAR (10)     NULL,
    [CSS_Attachment]                                             NVARCHAR (MAX) NULL,
    [User_ID]                                                    NVARCHAR (MAX) NULL,
    [Update_Date_Time]                                           DATETIME       CONSTRAINT [DF_Cooling_Work_Order_Update_Date_Time] DEFAULT (getdate()) NULL,
    [Loaded_Date]                                                DATETIME       NULL,
    [WO_Month]                                                   NCHAR (2)      NULL,
    [WO_Year]                                                    NCHAR (4)      NULL,
    [Month_Name]                                                 NVARCHAR (50)  NULL,
    [Services_Business_Unit]                                     VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_Work_Order_Number] PRIMARY KEY CLUSTERED ([Work_Order_Number] ASC)
);

