CREATE TABLE [dbo].[SE_CSS_PURCHASE_ORDER] (
    [Id]                            BIGINT          IDENTITY (1, 1) NOT NULL,
    [CSS_ID]                        BIGINT          NOT NULL,
    [PO_NO]                         VARCHAR (100)   NOT NULL,
    [PO_Date]                       DATETIME        NOT NULL,
    [HBN_WARRANTY_AMT]              NUMERIC (18, 2) NOT NULL,
    [Available_HBN_WARRANTY_AMT]    NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [HBN_AMC_AMT]                   NUMERIC (18, 2) NOT NULL,
    [Available_HBN_AMC_AMT]         NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [LABOR_AMC_AMT]                 NUMERIC (18, 2) NOT NULL,
    [Available_LABOR_AMC_AMT]       NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [SUPPLY_AMC_AMT]                NUMERIC (18, 2) NOT NULL,
    [Available_SUPPLY_AMC_AMT]      NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [LABOR_WARRANTY_AMT]            NUMERIC (18, 2) NOT NULL,
    [Available_LABOR_WARRANTY_AMT]  NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [SUPPLY_WARRANTY_AMT]           NUMERIC (18, 2) NOT NULL,
    [Available_SUPPLY_WARRANTY_AMT] NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [BASIC_AMT]                     NUMERIC (18, 2) NOT NULL,
    [Available_Basic_AMT]           NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [Valid_From]                    DATETIME        NOT NULL,
    [Valid_Till]                    DATETIME        NULL,
    [Status]                        VARCHAR (10)    NOT NULL,
    [Updated_User]                  VARCHAR (100)   NOT NULL,
    [Updated_Date]                  DATETIME        NOT NULL,
    [Remarks]                       VARCHAR (MAX)   NULL,
    [Month_Name]                    VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_SE_CSS_PURCHASE_ORDER] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PURCHASE_ORDER_CSS] FOREIGN KEY ([CSS_ID]) REFERENCES [dbo].[SE_CSS_MASTER] ([Id])
);

