CREATE TABLE [dbo].[SE_CSS_APPROVED_WORKORDER_Back_20220929] (
    [Id]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [Approved_Id]              BIGINT          NOT NULL,
    [WO_BusinessUnit]          VARCHAR (MAX)   NULL,
    [Work_Order_Number]        VARCHAR (MAX)   NULL,
    [Installed_At_Account]     VARCHAR (MAX)   NULL,
    [Month_Name]               VARCHAR (MAX)   NULL,
    [Work_Order_Type]          VARCHAR (MAX)   NULL,
    [WO_Completed_Date]        VARCHAR (MAX)   NULL,
    [Claim]                    DECIMAL (18, 2) NULL,
    [Labour_Cost]              DECIMAL (18, 2) NULL,
    [Supply_Cost]              DECIMAL (18, 2) NULL,
    [Gid]                      VARCHAR (MAX)   NOT NULL,
    [Case]                     NVARCHAR (MAX)  NULL,
    [First_Assigned_DateTime]  NVARCHAR (MAX)  NULL,
    [Main_Installed_Product]   NVARCHAR (MAX)  NULL,
    [IP_Serial_Number]         NVARCHAR (MAX)  NULL,
    [Product_Grouping]         NVARCHAR (10)   NULL,
    [Work_Order_Sub_Type]      NVARCHAR (MAX)  NULL,
    [Completed_On]             NVARCHAR (MAX)  NULL,
    [Work_Order_Reason]        NVARCHAR (MAX)  NULL,
    [Product]                  NVARCHAR (MAX)  NULL,
    [Is_Billable]              NVARCHAR (MAX)  NULL,
    [Non_Billing_Reason]       NVARCHAR (MAX)  NULL,
    [Street]                   NVARCHAR (MAX)  NULL,
    [City]                     NVARCHAR (MAX)  NULL,
    [Zip]                      NVARCHAR (MAX)  NULL,
    [State]                    NVARCHAR (MAX)  NULL,
    [Service_Team]             NVARCHAR (MAX)  NULL,
    [Primary_FSR]              NVARCHAR (MAX)  NULL,
    [Partner_Account]          NVARCHAR (MAX)  NULL,
    [Work_Performed]           NVARCHAR (MAX)  NULL,
    [WO_Process_Status]        BIGINT          NULL,
    [Distance_Slab]            NVARCHAR (MAX)  NULL,
    [Actual_Expense_converted] INT             NULL,
    [WO_Completed_Timestamp]   NVARCHAR (MAX)  NULL,
    [Claim_Type]               NVARCHAR (MAX)  NULL,
    [LABOUR_DESC]              VARCHAR (MAX)   NULL,
    [SUPPLY_DESC]              VARCHAR (MAX)   NULL,
    [MILEAGE_DESC]             VARCHAR (MAX)   NULL,
    [Actual_Expenses_Gas]      DECIMAL (18, 5) NULL,
    [Actual_Expenses_Mileage]  DECIMAL (18, 5) NULL,
    [Actual_Expenses_Supplies] DECIMAL (18, 5) NULL,
    [ACTUAL_LABOUR_COST]       DECIMAL (18, 2) NULL,
    [ACTUAL_SUPPLY_COST]       DECIMAL (18, 2) NULL,
    [Actual_Cost]              DECIMAL (20, 2) NULL,
    [CSS_Reason]               VARCHAR (MAX)   NULL
);

