CREATE TABLE [dbo].[SE_CurrentStatus] (
    [Id]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [CSS_Id]                BIGINT          NOT NULL,
    [CSS_CODE]              VARCHAR (MAX)   NULL,
    [CSS_NAME]              VARCHAR (MAX)   NULL,
    [BUSINESS_UNIT]         VARCHAR (MAX)   NULL,
    [VENDOR_CODE]           VARCHAR (MAX)   NULL,
    [EMAIL_ID]              VARCHAR (MAX)   NULL,
    [MonthName]             VARCHAR (MAX)   NULL,
    [Inv_No]                VARCHAR (MAX)   NULL,
    [Inv_Date]              DATETIME        NULL,
    [WO_COUNT]              INT             NULL,
    [Inv_Amt]               DECIMAL (18, 2) NULL,
    [CSS_APPROVED_DATE]     DATETIME        NULL,
    [CSS_MGR_APPROVED_DATE] DATETIME        NULL,
    [PRF_GEN_DATE]          DATETIME        NULL,
    [INVOICE_GEN_DATE]      DATETIME        NULL,
    [FIN_APPROVED_DATE]     DATETIME        NULL,
    [GRN_GEN_DATE]          DATETIME        NULL,
    [INVOICE_PAID_DATE]     DATETIME        NULL,
    [GID]                   VARCHAR (MAX)   NULL,
    [CREATED_DATE]          DATETIME        NOT NULL,
    [Central_Approved_date] DATETIME        NULL,
    [Tax_Amt]               DECIMAL (18, 2) NULL,
    [Inc_Tax_Amt]           DECIMAL (18, 2) NULL,
    [Region]                VARCHAR (MAX)   NULL,
    [Wo_Uploaded_Date]      DATETIME        NULL,
    [Invoice_Status_Type]   INT             NULL,
    CONSTRAINT [PK_SE_CurrentStatus] PRIMARY KEY NONCLUSTERED ([Id] ASC)
);

