CREATE TABLE [dbo].[SE_CSS_INVOICE] (
    [Id]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [CSS_ID]                  BIGINT          NOT NULL,
    [INV_TYPE]                VARCHAR (100)   NOT NULL,
    [WO_BUSINESSUNIT]         VARCHAR (100)   NOT NULL,
    [WO_AMT]                  NUMERIC (18, 2) NOT NULL,
    [BASE_PAYOUT]             NUMERIC (18, 2) CONSTRAINT [df_base] DEFAULT ((0)) NOT NULL,
    [INCENTIVE_AMT]           NUMERIC (18, 2) CONSTRAINT [df_incentive] DEFAULT ((0)) NOT NULL,
    [DED_AMT]                 NUMERIC (18, 2) CONSTRAINT [df_ded] DEFAULT ((0)) NOT NULL,
    [INV_AMT]                 NUMERIC (18, 2) CONSTRAINT [df_inv] DEFAULT ((0)) NOT NULL,
    [TAX_AMT]                 NUMERIC (18, 2) CONSTRAINT [df_tax] DEFAULT ((0)) NOT NULL,
    [INC_TAX_AMT]             NUMERIC (18, 2) CONSTRAINT [df_inctax] DEFAULT ((0)) NOT NULL,
    [PRF_NO]                  VARCHAR (100)   NULL,
    [PRF_Gen_Date]            DATETIME        NULL,
    [INV_NO]                  VARCHAR (100)   NULL,
    [INV_DATE]                DATETIME        NULL,
    [GRN_NO]                  VARCHAR (100)   NULL,
    [GRN_DATE]                DATETIME        NULL,
    [PO_ID]                   BIGINT          NULL,
    [NO_DUE_DATE]             DATETIME        NULL,
    [Payment_Process_Date]    DATETIME        NULL,
    [Status_Type]             INT             NOT NULL,
    [Updated_User]            VARCHAR (100)   NOT NULL,
    [Updated_Date]            DATETIME        NOT NULL,
    [Remarks]                 VARCHAR (MAX)   NULL,
    [WO_COUNT]                BIGINT          DEFAULT ((0)) NOT NULL,
    [INV_Attachment]          VARCHAR (MAX)   NULL,
    [CSS_INV_AMT]             DECIMAL (18, 2) NULL,
    [INV_GEN_DATE]            DATETIME        NULL,
    [FIN_APPROVE_DATE]        DATETIME        NULL,
    [PO_REQ_DATE]             DATETIME        NULL,
    [PO_ASSIGN_DATE]          DATETIME        NULL,
    [GRN_GEN_DATE]            DATETIME        NULL,
    [INV_PAID_DATE]           DATETIME        NULL,
    [Month_Name]              VARCHAR (100)   DEFAULT ('') NOT NULL,
    [IsGRNCollectoreMailSent] BIT             NULL,
    [Created_Date]            DATETIME        DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_SE_CSS_INVOICE] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_INVOICE_CSS] FOREIGN KEY ([CSS_ID]) REFERENCES [dbo].[SE_CSS_MASTER] ([Id]),
    CONSTRAINT [FK_INVOICE_PO] FOREIGN KEY ([PO_ID]) REFERENCES [dbo].[SE_CSS_PURCHASE_ORDER] ([Id])
);

