CREATE TABLE [dbo].[SE_GRADATION_MASTER] (
    [Id]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [GRADATION_TYPE] VARCHAR (100)   NOT NULL,
    [CSS_PAYOUT]     VARCHAR (100)   NOT NULL,
    [GRADE]          VARCHAR (100)   NOT NULL,
    [GRADE_PERCENT]  NUMERIC (18, 2) NOT NULL,
    [Updated_User]   VARCHAR (100)   NOT NULL,
    [Updated_Date]   DATETIME        NOT NULL,
    CONSTRAINT [PK_SE_GRADATION_MASTER] PRIMARY KEY NONCLUSTERED ([Id] ASC)
);

