CREATE TABLE [dbo].[SE_Work_Order] (
    [Id]                                BIGINT          IDENTITY (1, 1) NOT NULL,
    [WO_BusinessUnit]                   NVARCHAR (100)  NOT NULL,
    [Work_Order_Number]                 NVARCHAR (50)   NOT NULL,
    [CSS_Id]                            BIGINT          NOT NULL,
    [Case]                              NVARCHAR (MAX)  NULL,
    [PRF_Number]                        NVARCHAR (50)   NULL,
    [First_Assigned_DateTime]           NVARCHAR (MAX)  NULL,
    [Customer_Requested_Date]           NVARCHAR (MAX)  NULL,
    [FSR_Internal_Comments]             NVARCHAR (MAX)  NULL,
    [WO_Created_Date_Time]              NVARCHAR (MAX)  NULL,
    [Main_Installed_Product]            NVARCHAR (MAX)  NULL,
    [Product]                           NVARCHAR (MAX)  NULL,
    [Product_Commercial_Reference]      NVARCHAR (MAX)  NULL,
    [Product_Grouping]                  NVARCHAR (10)   NULL,
    [IP_Serial_Number]                  NVARCHAR (MAX)  NULL,
    [Work_Order_Reason]                 NVARCHAR (MAX)  NULL,
    [Work_Order_Created_Date]           NVARCHAR (MAX)  NULL,
    [Completed_On]                      NVARCHAR (MAX)  NULL,
    [Is_Billable]                       NVARCHAR (MAX)  NULL,
    [Is_RepeatCall_NonMaterial]         BIT             NULL,
    [Non_Billing_Reason]                NVARCHAR (MAX)  NULL,
    [Installed_At_Account]              NVARCHAR (MAX)  NULL,
    [Street]                            NVARCHAR (MAX)  NULL,
    [City]                              NVARCHAR (MAX)  NULL,
    [Zip]                               NVARCHAR (MAX)  NULL,
    [State]                             NVARCHAR (MAX)  NULL,
    [Service_Team]                      NVARCHAR (MAX)  NULL,
    [Primary_FSR]                       NVARCHAR (MAX)  NULL,
    [Partner_Account]                   NVARCHAR (MAX)  NULL,
    [Partner_Account_Rv]                NVARCHAR (MAX)  NULL,
    [Work_Performed]                    NVARCHAR (MAX)  NULL,
    [Work_Order_Type]                   NVARCHAR (MAX)  NULL,
    [Contact]                           NVARCHAR (MAX)  NULL,
    [Contact_Phone]                     NVARCHAR (MAX)  NULL,
    [Work_Order_Sub_Type]               NVARCHAR (MAX)  NULL,
    [Work_Order_Status]                 NVARCHAR (MAX)  NULL,
    [WO_Completed_Timestamp]            NVARCHAR (MAX)  NULL,
    [Comments_to_Planner]               NVARCHAR (MAX)  NULL,
    [Special_Instructions]              NVARCHAR (MAX)  NULL,
    [Actual_Expense_converted]          INT             NULL,
    [Actual_Expense_converted_Currency] NVARCHAR (MAX)  NULL,
    [Actual_Expense]                    NVARCHAR (MAX)  NOT NULL,
    [Claim_Type]                        NVARCHAR (MAX)  NULL,
    [Branch_Code]                       NVARCHAR (MAX)  NULL,
    [Payout_Type]                       NVARCHAR (MAX)  NULL,
    [Region]                            NVARCHAR (MAX)  NULL,
    [Call_type]                         NVARCHAR (MAX)  NULL,
    [Call_type_rv]                      NVARCHAR (MAX)  NULL,
    [IsMaterialUsed]                    BIT             CONSTRAINT [DF_SE_Work_Order_IsMaterialUsed] DEFAULT ((0)) NULL,
    [PRODUCT_CATEGORY]                  NVARCHAR (MAX)  NULL,
    [Distance_Slab]                     NVARCHAR (MAX)  NULL,
    [Repeat_Yes_No]                     NVARCHAR (MAX)  NULL,
    [Claim]                             DECIMAL (18, 2) NULL,
    [Remarks]                           NVARCHAR (MAX)  NULL,
    [Region_Remarks]                    NVARCHAR (MAX)  NULL,
    [Bill_Cycle]                        NVARCHAR (MAX)  NULL,
    [Business_Unit]                     NVARCHAR (MAX)  NULL,
    [DS_Code]                           NVARCHAR (MAX)  NULL,
    [MaterialUsed]                      NVARCHAR (MAX)  NULL,
    [Is_Expenses_Mileage]               BIT             NULL,
    [Actual_Expenses_Mileage]           DECIMAL (18, 5) NULL,
    [Is_Expenses_Gas]                   BIT             NULL,
    [Actual_Expenses_Gas]               DECIMAL (18, 5) NULL,
    [Is_Expenses_Supplies]              BIT             NULL,
    [Actual_Expenses_Supplies]          DECIMAL (18, 5) NULL,
    [LABOUR_COST]                       DECIMAL (18, 2) NULL,
    [SUPPLY_COST]                       DECIMAL (18, 2) NULL,
    [AMC_WARRANTY_FLAG]                 VARCHAR (100)   NULL,
    [Actual_Cost]                       DECIMAL (20, 2) NULL,
    [Central_Status]                    BIT             NULL,
    [Central_UpdatedDate]               DATETIME        NULL,
    [Central_User]                      NVARCHAR (100)  NULL,
    [CSS_Status]                        BIT             NULL,
    [CSS_UpdatedDate]                   DATETIME        NULL,
    [CSS_User]                          NVARCHAR (100)  NULL,
    [CSS_Remark]                        NVARCHAR (MAX)  NULL,
    [CSS_Cost]                          DECIMAL (20, 2) NULL,
    [CSS_Mgr_Status]                    BIT             NULL,
    [CSS_Mgr_UpdatedDate]               DATETIME        NULL,
    [CSS_Mgr_User]                      NVARCHAR (100)  NULL,
    [CSS_Mgr_Remark]                    NVARCHAR (MAX)  NULL,
    [CSS_Mgr_Cost]                      DECIMAL (20, 2) NULL,
    [WO_Process_Status]                 BIGINT          NULL,
    [INV_ID]                            BIGINT          NULL,
    [User_ID]                           NVARCHAR (MAX)  NULL,
    [Update_Date_Time]                  DATETIME        CONSTRAINT [DF_SE_Work_Order_Update_Date_Time] DEFAULT (getdate()) NULL,
    [Loaded_Date]                       DATETIME        NULL,
    [WO_Month]                          NVARCHAR (2)    NULL,
    [WO_Year]                           NVARCHAR (4)    NULL,
    [Month_Name]                        VARCHAR (50)    NOT NULL,
    [SUPPLY_INV_ID]                     BIGINT          NULL,
    [CSS_Reason]                        VARCHAR (MAX)   NULL,
    [CSS_Reason_Desc]                   VARCHAR (MAX)   NULL,
    [CSS_Attachment]                    VARCHAR (MAX)   NULL,
    [CSS_Mgr_Reason]                    VARCHAR (MAX)   NULL,
    [CSS_Mgr_Reason_Desc]               VARCHAR (MAX)   NULL,
    [CSS_Mgr_Attachment]                VARCHAR (MAX)   NULL,
    [CSS_APPROVED_DATE]                 DATETIME        NULL,
    [LABOUR_DESC]                       VARCHAR (MAX)   NULL,
    [SUPPLY_DESC]                       VARCHAR (MAX)   NULL,
    [MILEAGE_DESC]                      VARCHAR (MAX)   NULL,
    [ACTUAL_LABOUR_COST]                DECIMAL (18, 2) NULL,
    [ACTUAL_SUPPLY_COST]                DECIMAL (18, 2) NULL,
    [CSS_LABOUR_COST]                   DECIMAL (18, 2) NULL,
    [CSS_SUPPLY_COST]                   DECIMAL (18, 2) NULL,
    [CSS_MGR_LABOUR_COST]               DECIMAL (18, 2) NULL,
    [CSS_MGR_SUPPLY_COST]               DECIMAL (18, 2) NULL,
    [Services_Business_Unit]            VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_SE_Work_Order] PRIMARY KEY NONCLUSTERED ([Id] ASC),
    CONSTRAINT [FK_WO_CSS] FOREIGN KEY ([CSS_Id]) REFERENCES [dbo].[SE_CSS_MASTER] ([Id]),
    CONSTRAINT [FK_WO_INVOICE] FOREIGN KEY ([INV_ID]) REFERENCES [dbo].[SE_CSS_INVOICE] ([Id]),
    CONSTRAINT [FK_WO_SUPPLYINVOICE] FOREIGN KEY ([SUPPLY_INV_ID]) REFERENCES [dbo].[SE_CSS_INVOICE] ([Id])
);

