CREATE TABLE [dbo].[temp_SE_CSS_Master] (
    [Id]                                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [Region]                              NVARCHAR (MAX)  NULL,
    [CSS_Name_as_per_Oracle_SAP]          NVARCHAR (MAX)  NULL,
    [CSS_Name_in_bFS_to_be_referred]      NVARCHAR (MAX)  NULL,
    [CSS_Manager]                         NVARCHAR (MAX)  NULL,
    [Vendor_Code]                         NVARCHAR (MAX)  NULL,
    [CSS_Code]                            NVARCHAR (MAX)  NULL,
    [Email_ID]                            NVARCHAR (MAX)  NULL,
    [Pay_out_Type]                        NVARCHAR (MAX)  NULL,
    [Pay_out_Structure]                   NVARCHAR (MAX)  NULL,
    [Business_Unit]                       NVARCHAR (MAX)  NULL,
    [City_Location]                       NVARCHAR (MAX)  NULL,
    [State]                               NVARCHAR (MAX)  NULL,
    [CSS_Country]                         NVARCHAR (MAX)  NULL,
    [Finance_Claim_Data_Validator]        NVARCHAR (MAX)  NULL,
    [Invoice_Validator_from_Finance_Team] NVARCHAR (MAX)  NULL,
    [HBN_WARRANTY]                        NVARCHAR (MAX)  NULL,
    [HBN_AMC]                             NVARCHAR (MAX)  NULL,
    [AMC_LABOR]                           NVARCHAR (MAX)  NULL,
    [AMC_SUPPLY]                          NVARCHAR (MAX)  NULL,
    [WARRANTY_LABOR]                      NVARCHAR (MAX)  NULL,
    [WARRANTY_SUPPLY]                     NVARCHAR (MAX)  NULL,
    [PO]                                  NVARCHAR (MAX)  NULL,
    [WH_Location]                         NVARCHAR (MAX)  NULL,
    [PO_Type]                             NVARCHAR (MAX)  NULL,
    [CSS_City_Class]                      NVARCHAR (MAX)  NULL,
    [CSS_MGR_USER_ID]                     NVARCHAR (450)  NULL,
    [INV_FIN_USER_ID]                     NVARCHAR (450)  NULL,
    [GRN_USER_ID]                         NVARCHAR (450)  NULL,
    [AUTHORIZED_EMAILS]                   NVARCHAR (MAX)  NULL,
    [Primary_Contact_Person]              VARCHAR (MAX)   NULL,
    [Phone_Number]                        VARCHAR (MAX)   NULL,
    [Authorised_UserEmail]                VARCHAR (MAX)   NULL,
    [Grade]                               VARCHAR (MAX)   NULL,
    [Base_Payout_Percentage]              DECIMAL (18, 2) NULL,
    [Incentive_Percentage]                DECIMAL (18, 2) NULL,
    [CSS_Manager_Email_ID]                VARCHAR (MAX)   NULL,
    [Contact_Person_Name]                 VARCHAR (MAX)   NULL,
    [Contact_Person_Email_ID]             VARCHAR (MAX)   NULL,
    [Finance_Head]                        VARCHAR (MAX)   NULL,
    [Finance_Head_Email_ID]               VARCHAR (MAX)   NULL,
    [GRN_Creater]                         VARCHAR (MAX)   NULL,
    [SCM_Head]                            VARCHAR (MAX)   NULL,
    [GRN_Creater_Email_ID]                VARCHAR (MAX)   NULL,
    [SCM_Head_Email_ID]                   VARCHAR (MAX)   NULL
);

